import { describe, expect, it, vi } from 'vitest'
import { AppSpaceHandoffs } from './app-space-handoffs'
describe('App Space handoff tokens', () => {
  it('acknowledges more than 250000 items with a compact token, then retires all of them on superseding', () => {
    const removed = vi.fn()
    const handoffs = new AppSpaceHandoffs(removed)
    const ids = Array.from({ length: 250001 }, (_, index) => `item-${index}`)
    handoffs.begin(null)
    const previous = handoffs.create(ids)
    handoffs.settle(previous, previous)
    expect(removed).not.toHaveBeenCalled()
    handoffs.begin(previous)
    const next = handoffs.create(['new-item'])
    handoffs.settle(next, next)
    expect(removed).toHaveBeenCalledExactlyOnceWith(ids)
  })
  it('preserves the current plan on cancellation and bounds repeated abandoned drafts', () => {
    const removed = vi.fn()
    const handoffs = new AppSpaceHandoffs(removed)
    const current = handoffs.create(['current'])
    handoffs.settle(current, current)
    handoffs.begin(current)
    const canceled = handoffs.create(['canceled'])
    handoffs.settle(canceled, current)
    expect(removed).toHaveBeenLastCalledWith(['canceled'])
    handoffs.begin(current)
    const abandoned = handoffs.create(['abandoned'])
    handoffs.begin(current)
    const latest = handoffs.create(['latest'])
    expect(removed).toHaveBeenLastCalledWith(['abandoned'])
    handoffs.settle(abandoned, current)
    handoffs.settle(latest, current)
    expect(removed.mock.calls.flat(2)).toEqual(['canceled', 'abandoned', 'latest'])
  })
  it('ignores late success acknowledgements when a newer draft is already being reviewed', () => {
    const removed = vi.fn()
    const handoffs = new AppSpaceHandoffs(removed)
    const previous = handoffs.create(['previous'])
    handoffs.settle(previous, previous)
    handoffs.begin(previous)
    const next = handoffs.create(['next'])
    handoffs.settle(previous, previous)
    expect(removed).not.toHaveBeenCalled()
    handoffs.settle(next, next)
    expect(removed).toHaveBeenCalledExactlyOnceWith(['previous'])
  })
  it('never retires unrelated cleaner IDs or accepts arbitrary tokens', () => {
    const removed = vi.fn()
    const handoffs = new AppSpaceHandoffs(removed)
    const own = handoffs.create(['owned'])
    expect(() => handoffs.begin('unrelated-cleaner-id')).toThrow('Unknown')
    expect(removed).not.toHaveBeenCalled()
    handoffs.settle(own, null)
    expect(removed).toHaveBeenCalledExactlyOnceWith(['owned'])
  })
})
